"""
Evaluate the logistic regression book recommender on test set.

This script loads our trained logistic regression recommendation model along
with precomputed data required for evaluation, including:

    - a sparse user-book interaction matrix for the test users
    - a book-book similarity matrix
    - book popularity statistics (average rating and log number of ratings)
    - a ground-truth book for each test user

A subset of 10,000 test users with valid held-out books are randomly sampled and used to
evaluate recommendation quality. The evaluation computes the Hit@50 metric,
which measures the proportion of users whose held-out book appears in the
top 50 recommendations produced by the model.

Compares the model performance against a simple popularity-based baseline ranking, 
avg. rating*log(num. ratings). Note every book has at least one rating. 

Returns:
    Model Hit@50: 0.0582 = 5.82% of users had their held-out book in the top 50 recommendations 
    from the logistic regression model.
    
    Popularity Hit@50: 0.0003 = 0.03% of users had their held-out book in the top 50 most 
    popular books.

Usage:
    Run script from the project root using:
    python -m backend.recommender.recommender_test

Time:
    ~20 minutes due to ~1M books by 10,000 users scoring
"""


import os
from time import time

import joblib
import numpy as np
from scipy.sparse import load_npz, csr_matrix

from data.scripts.config import PROCESSED_DIR
from backend.recommender.config import RECOMMENDER_DIR

np.random.seed(42)

MODEL_FILE = os.path.join(RECOMMENDER_DIR, "book_recommender_model.pkl")
MODEL_SCALER_FILE = os.path.join(RECOMMENDER_DIR, "feature_scaler.pkl")
USER_TEST_FILE = os.path.join(PROCESSED_DIR, "test_matrix.npz")
BOOK_SIM_FILE = os.path.join(PROCESSED_DIR, "book_similarity.npz")
BOOK_RATINGS_FILE = os.path.join(PROCESSED_DIR, "book_ratings.npz")
GROUND_TRUTH_FILE = os.path.join(PROCESSED_DIR, "test_ground_truth.npy")

USER_LIBRARY_MATRIX_TEST = load_npz(USER_TEST_FILE).tocsr()
BOOK_SIMILARITY_MATRIX = load_npz(BOOK_SIM_FILE).tocsc()
ratings_file = np.load(BOOK_RATINGS_FILE)
BOOK_AVG_RATINGS_VECTOR = ratings_file["ratings_avg"].astype(np.float32)
BOOK_NUMBER_RATINGS_VECTOR = np.log1p(ratings_file["log_number_ratings"]).astype(np.float32)
USER_GROUND_TRUTH_BOOK_TEST = np.load(GROUND_TRUTH_FILE).flatten()
print("Data loaded successfully.")

def hit50_evaluation_logistic(
    clf,
    user_library_sparse: csr_matrix,
    ground_truth: np.ndarray,
    book_similarity_sparse,
    book_avg_ratings: np.ndarray,
    book_num_ratings: np.ndarray,
    top_k: int = 50,
    block_size: int = 50000
):
    """
    To evaluate our logistic model recommendations we compute the proportion of user's who
    ground truth books appeared in their top 50 recommendations. We compare our models performance
    to a simple popularity based ranking heurist, metric book_avg_ratings + log(book_num_ratings).

    Args:
        clf : sklearn.linear_model.LogisticRegression
            Model coefficients in order:
                0: average similarity between candidate book and user's library
                1: book average rating
                2: log(number of ratings for the book)
                3: interaction between similarity and log(user library size)

        user_library_sparse : scipy.sparse.csr_matrix
            Sparse matrix of shape (n_users, n_books) representing the books each
            user has interacted with in the training data. A value of 1 indicates
            that the user has previously interacted with that book.

        ground_truth : numpy.ndarray
            Array of shape (n_users,) or (n_users, k) containing the held-out
            book index for each user used for evaluation. These are the books that
            were intentionally removed from the training interactions and the
            recommender is expected to recover.

        book_similarity_sparse : scipy.sparse matrix
            Sparse book-book similarity matrix of shape (n_books, n_books).
            Entry (i, j) represents similarity between book i and book j.

        book_avg_ratings : numpy.ndarray
            Array of shape (n_books,) containing the average rating for each book.

        book_num_ratings : numpy.ndarray
            Array of shape (n_books,) containing the number of ratings each book
            has received.

        top_k : int, default=50
            Number of recommendations to keep per user when computing the Hit@K
            evaluation metric.

        block_size : int, default=50000
            Number of books processed in each evaluation block.

        Returns:
        model_hit_rate : float
            Fraction of users whose held-out book appears in the top-K
            recommendations generated by the logistic regression model.

        popularity_hit_rate : float
            Fraction of users whose held-out book appears in the top-K most
            popular books according to the baseline popularity score.

        Algorithm Notes:
        1. Blockwise candidate evaluation:
        Instead of scoring all books at once, the function processes books in
        blocks of size block_size. This avoids allocating a full dense
        (n_users by n_books) matrix in memory.

        2. Vectorized similarity computation:
        For each block of candidate books, similarity between user libraries
        and candidate books is computed using sparse matrix multiplication.

        3. Incremental top-K selection:
        Instead of storing scores for all books, the algorithm maintains only
        the top-K recommendations for each user. After each block is scored,
        the new candidate scores are merged with the current top-K and
        we keep only the highest K values overall.
        *This reduces memory usage from O(n_users by n_books) to O(n_users by K).

        7. Hit@K evaluation:
        After all blocks have been processed, the function checks whether the
        held-out ground truth book for each user appears within their final
        top-K recommendation list. The fraction of users for which this occurs
        is reported as the Hit@K score.
        """

    beta = clf.coef_[0]
    beta_scaled = beta / scaler.scale_

    n_users = user_library_sparse.shape[0]
    n_books = book_similarity_sparse.shape[1]

    popularity_score = np.log1p(book_avg_ratings * book_num_ratings)
    log_lib_sizes = np.log1p(np.array(user_library_sparse.sum(axis=1)).ravel())

    best_scores_model = np.full((n_users, top_k), -np.inf, dtype=np.float32)
    best_books_model = np.full((n_users, top_k), -1, dtype=np.int32)

    best_scores_pop = np.full((n_users, top_k), -np.inf, dtype=np.float32)
    best_books_pop = np.full((n_users, top_k), -1, dtype=np.int32)

    start_time = time()

    user_rows, user_cols = user_library_sparse.nonzero()

    for start in range(0, n_books, block_size):
        end = min(start + block_size, n_books)
        book_ids = np.arange(start, end)

        sim_block = user_library_sparse @ book_similarity_sparse[:, start:end]
        sim_block = sim_block.toarray().astype(np.float32)
        user_lib_size = np.maximum(1, np.array(user_library_sparse.sum(axis=1)).ravel())
        sim_block /= user_lib_size[:, None]
        sim_lib_interaction = np.log1p(sim_block * log_lib_sizes[:, None])

        pop_block = popularity_score[start:end].astype(np.float32)

        score_block = (
            beta_scaled[0] * sim_block +
            beta_scaled[1] * pop_block +
            beta_scaled[2] * sim_lib_interaction
            )

        mask_in_block = (user_cols >= start) & (user_cols < end)
        rows_in_block = user_rows[mask_in_block]
        cols_in_block = user_cols[mask_in_block] - start
        score_block[rows_in_block, cols_in_block] = -np.inf
        pop_block[cols_in_block] = -np.inf

        for u_idx in range(n_users):
            combined_scores = np.concatenate([best_scores_model[u_idx], score_block[u_idx]])
            combined_books = np.concatenate([best_books_model[u_idx], book_ids])
            top_idx = np.argpartition(-combined_scores, top_k)[:top_k]
            best_scores_model[u_idx] = combined_scores[top_idx]
            best_books_model[u_idx] = combined_books[top_idx]

            combined_scores_pop = np.concatenate([best_scores_pop[u_idx], pop_block])
            combined_books_pop = np.concatenate([best_books_pop[u_idx], book_ids])
            top_idx_pop = np.argpartition(-combined_scores_pop, top_k)[:top_k]
            best_scores_pop[u_idx] = combined_scores_pop[top_idx_pop]
            best_books_pop[u_idx] = combined_books_pop[top_idx_pop]

        print(f"Processed books {start}-{end} / {n_books}")

    hits_model = [ground_truth[u] in best_books_model[u] for u in range(n_users)]
    pop_top_k_idx = np.argpartition(-popularity_score, top_k)[:top_k]
    hits_pop = [ground_truth[u] in pop_top_k_idx for u in range(n_users)]

    print("Final Results")
    print(f"Model Hit@{top_k}: {np.mean(hits_model):.4f}")
    print(f"Popularity Hit@{top_k}: {np.mean(hits_pop):.4f}")
    print(f"Total elapsed time: {time()-start_time:.1f}s")

    return np.mean(hits_model), np.mean(hits_pop)

CLF = joblib.load(MODEL_FILE)
scaler = joblib.load(MODEL_SCALER_FILE)
print("Logistic model loaded.")

N_USERS = 10000
valid_users = np.where(USER_GROUND_TRUTH_BOOK_TEST != -1)[0]
sample_users = np.random.choice(
    valid_users, size=min(N_USERS, len(valid_users)), replace=False
)
user_library_batch = USER_LIBRARY_MATRIX_TEST[sample_users]
ground_truth_batch = USER_GROUND_TRUTH_BOOK_TEST[sample_users]

def main():
    """
    Main function to run the Hit@50 evaluation for the logistic regression recommender model.
    """
    hit50_evaluation_logistic(
        clf=CLF,
        user_library_sparse=user_library_batch,
        ground_truth=ground_truth_batch,
        book_similarity_sparse=BOOK_SIMILARITY_MATRIX,
        book_avg_ratings=BOOK_AVG_RATINGS_VECTOR,
        book_num_ratings=BOOK_NUMBER_RATINGS_VECTOR
        )

if __name__ == "__main__":
    main()
