"""
Train a logistic regression model for book recommendation using implicit feedback.

This script constructs a training set using observed user-book interactions as
positive examples and randomly sampled unread books as negative examples.
Features are computed from item popularity statistics and similarity scores
between a user's library and candidate books.

The model learns a global logistic regression that predicts the probability
that a user will interact with a book. At recommendation time, books are ranked
by predicted score for each user.

Key Features:
    - Book similarity to a user's existing library
    - Average book rating
    - Log number of ratings (book popularity)
    - Interaction between similarity and user library size

Assumptions / Limitations:
    - Observed interactions are treated as positive feedback; non-interactions
      are assumed to be negative feedback when sampled.
    - Some negatives may actually be unobserved positives which introduces noise.
    - Predictions are used for ranking rather than calibrated probabilities.
Usage:
    Run script from the project root using:
    python -m backend.recommender.recomender_fitting
    
Time: ~9 minutes to run

Output:
Learned coefficients: [similarity: -0.2672652, avg_rating: 0.32307223, 
                      number_ratings: 0.92024347, user_library_size*similarity: 3.11933843]
"""


import os
import numpy as np
from scipy.sparse import load_npz
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
import joblib

from data.scripts.config import PROCESSED_DIR
from backend.recommender.config import RECOMMENDER_DIR

np.random.seed(42)

OUTPUT_MODEL_FILE = os.path.join(RECOMMENDER_DIR, "book_recommender_model.pkl")
OUTPUT_MODEL_SCALER_FILE = os.path.join(RECOMMENDER_DIR, "feature_scaler.pkl")

npzfile = np.load(os.path.join(PROCESSED_DIR, "book_ratings.npz"))
BOOK_AVG_RATINGS_VECTOR = npzfile["ratings_avg"]
BOOK_NUMBER_RATINGS_VECTOR = npzfile["log_number_ratings"]
BOOK_SIMILARITY_MATRIX = load_npz(os.path.join(PROCESSED_DIR, "book_similarity.npz")).tocsc()

USER_LIBRARY_MATRIX_TRAIN = load_npz(os.path.join(PROCESSED_DIR, "train_matrix.npz")).tocsr()
USER_GROUND_TRUTH_BOOK_TRAIN = np.load(os.path.join(PROCESSED_DIR,
                                                    "train_ground_truth.npy")).flatten()

print("Data loaded successfully.")


def sample_negative_books(
    users,
    ground_truth,
    user_library_matrix,
    n_books,
    n_neg=5
):
    """
    Generate negative book samples for users.

    For each user, samples n_neg books that:
        - are not in the user's library
        - are not in the user's held-out ground truth

    Works for a single or multiple ground-truth books per user.

    Args:
        users: Indices of users to sample negatives for.
        ground_truth (np.ndarray or list): Held-out book indices for each user. Can be scalar or
        array per user.
        user_library_matrix (scipy.sparse.csr_matrix): User-book interaction matrix.
        n_books (int): Total number of books (upper bound for sampling indices).
        n_neg (int, default=5): Number of negative samples per user.

    Returns:
        np.ndarray: Array of shape (len(users), n_neg) containing negative book indices for each
        user.
    """

    neg_books = np.empty((len(users), n_neg), dtype=np.int32)

    for i, u in enumerate(users):

        library = user_library_matrix[u].indices

        gt = ground_truth[i]
        if np.isscalar(gt):
            gt_set = {gt} if gt != -1 else set()
        else:
            gt_set = set(gt[gt != -1])

        forbidden = set(library) | gt_set

        samples = []
        while len(samples) < n_neg:
            candidate = np.random.randint(0, n_books)
            if candidate not in forbidden:
                samples.append(candidate)

        neg_books[i] = samples

    return neg_books


def build_training_set(
    ground_truth,
    user_library_matrix=USER_LIBRARY_MATRIX_TRAIN,
    book_similarity_matrix=BOOK_SIMILARITY_MATRIX,
    book_avg_ratings_vector=BOOK_AVG_RATINGS_VECTOR,
    book_number_ratings_vector=BOOK_NUMBER_RATINGS_VECTOR,
    n_neg=5,
    batch_size=10000
):
    """
    Construct feature matrix and labels used to train model.

    Positive examples correspond to observed user-book interactions. For each
    positive example, a set of negative examples is generated by sampling books
    the user has not interacted with.

    Features are computed for each (user, book) pair using similarity scores
    and book statistics.

    Args:
        user_book_matrix : scipy.sparse.csr_matrix
            Sparse user-book interaction matrix.
        sim_scores : numpy.ndarray
            Precomputed user-book similarity scores.
        avg_ratings : numpy.ndarray
            Average rating per book.
        num_ratings : numpy.ndarray
            Number of ratings per book.
        log_library_sizes : numpy.ndarray
            Log library size per user.
        n_neg : int
            Number of negative samples per positive interaction.

    Returns:
        X : numpy.ndarray
            Feature matrix for training.
            Features include similarity score, average rating, log number of ratings, 
            and interaction term.
        y : numpy.ndarray
            Binary labels (1 = positive interaction, 0 = sampled negative).

    Notes:
        - Multiple ground truth positives per user are supported.
    """

    train_users_idx = np.where(ground_truth != -1)[0]

    x_rows = []
    y_rows = []

    n_books = book_similarity_matrix.shape[1]

    for start in range(0, len(train_users_idx), batch_size):

        batch_users = train_users_idx[start:start + batch_size]
        b = len(batch_users)

        batch_ground_truth = ground_truth[batch_users]

        user_lib = user_library_matrix[batch_users]

        library_sizes = np.maximum(user_lib.sum(axis=1).A1, 1)
        log_library_sizes = np.log1p(library_sizes)

        neg_books = sample_negative_books(
            batch_users,
            batch_ground_truth,
            user_library_matrix,
            n_books,
            n_neg
        )

        books_to_compute = np.concatenate(
            [batch_ground_truth[:, None], neg_books],
            axis=1
        )

        n_samples = books_to_compute.shape[1]

        sim_scores = np.zeros((b, n_samples), dtype=np.float32)
        avg_ratings = np.zeros((b, n_samples), dtype=np.float32)
        num_ratings = np.zeros((b, n_samples), dtype=np.float32)

        for j in range(n_samples):

            books = books_to_compute[:, j]

            sim_raw = user_lib.dot(book_similarity_matrix[:, books]).diagonal()

            sim_scores[:, j] = sim_raw / library_sizes
            avg_ratings[:, j] = book_avg_ratings_vector[books]
            num_ratings[:, j] = book_number_ratings_vector[books]
        positives = np.column_stack([
           sim_scores[:, 0],
           avg_ratings[:, 0],
           num_ratings[:, 0],
           sim_scores[:, 0] * log_library_sizes
           ])

        negatives = np.column_stack([
            sim_scores[:, 1:].ravel(),
            avg_ratings[:, 1:].ravel(),
            num_ratings[:, 1:].ravel(),
            (sim_scores[:, 1:] * log_library_sizes[:, None]).ravel()
            ])

        x_batch = np.vstack([positives, negatives])
        y_batch = np.concatenate([np.ones(b), np.zeros(b * (n_samples - 1))])

        x_rows.append(x_batch)
        y_rows.append(y_batch)

        if start // batch_size % 10 == 0:
            print(f"Processed {start:,} users")

    x = np.vstack(x_rows).astype(np.float32)
    y = np.concatenate(y_rows).astype(np.int8)

    return x, y


def train_logistic_model(
    ground_truth=USER_GROUND_TRUTH_BOOK_TRAIN,
    batch_size=10000,
    n_neg=5,
    output_model_file=OUTPUT_MODEL_FILE,
    output_scaler_file=OUTPUT_MODEL_SCALER_FILE
):
    """
    Train logistic regression model and save model + scaler.
    """

    x_train, y_train = build_training_set(
        ground_truth=ground_truth,
        batch_size=batch_size,
        n_neg=n_neg
    )

    scaler = StandardScaler()

    x_train_scaled = scaler.fit_transform(x_train)

    clf = LogisticRegression(solver="lbfgs", max_iter=1000)

    clf.fit(x_train_scaled, y_train)

    print("Learned coefficients:", clf.coef_[0])

    joblib.dump(clf, output_model_file)
    joblib.dump(scaler, output_scaler_file)

    return clf, scaler


def main():
    """
    Main function to train the logistic regression model.
    """

    train_logistic_model(n_neg=20)


if __name__ == "__main__":
    main()
