"""Mock data used by the Streamlit Bookish UI."""

books = [
    {
        "id": 1,
        "title": "The House in the Cerulean Sea",
        "author": "TJ Klune",
        "cover": "https://covers.openlibrary.org/b/isbn/9781250217318-L.jpg",
        "rating": 4.5,
        "rating_count": 12847,
        "genres": ["Fantasy", "Fiction", "LGBTQ+"],
        "description": "A by-the-book caseworker is sent to an orphanage for magical children and finds his life transformed by the six extraordinary kids and the mysterious man who runs the place.",
        "spl_available": True,
        "spl_branches": ["Central Library", "Capitol Hill", "Ballard"],
        "checkouts": 342,
        "clubs_reading": 3,
    },
    {
        "id": 2,
        "title": "Project Hail Mary",
        "author": "Andy Weir",
        "cover": "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
        "rating": 4.7,
        "rating_count": 28463,
        "genres": ["Science Fiction", "Adventure"],
        "description": "Ryland Grace is the sole survivor on a desperate last-chance mission and if he fails, humanity and the Earth itself are finished.",
        "spl_available": True,
        "spl_branches": ["Central Library", "University", "Beacon Hill"],
        "checkouts": 891,
        "clubs_reading": 5,
    },
    {
        "id": 3,
        "title": "Piranesi",
        "author": "Susanna Clarke",
        "cover": "https://covers.openlibrary.org/b/isbn/9781635575941-L.jpg",
        "rating": 4.3,
        "rating_count": 8921,
        "genres": ["Fantasy", "Mystery", "Literary Fiction"],
        "description": "Piranesi lives in the House. Perhaps he always has. The House is full of wonders: infinite halls, an ocean, hundreds of statues.",
        "spl_available": True,
        "spl_branches": ["Central Library", "Fremont"],
        "checkouts": 267,
        "clubs_reading": 2,
    },
    {
        "id": 4,
        "title": "Atomic Habits",
        "author": "James Clear",
        "cover": "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
        "rating": 4.4,
        "rating_count": 45231,
        "genres": ["Self-Help", "Productivity", "Non-Fiction"],
        "description": "An easy and proven way to build good habits and break bad ones with tiny changes that deliver remarkable results.",
        "spl_available": True,
        "spl_branches": ["Central Library", "Columbia City", "Greenwood"],
        "checkouts": 1203,
        "clubs_reading": 4,
    },
    {
        "id": 5,
        "title": "The Midnight Library",
        "author": "Matt Haig",
        "cover": "https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg",
        "rating": 4.2,
        "rating_count": 19345,
        "genres": ["Fiction", "Fantasy", "Contemporary"],
        "description": "Between life and death there is a library, and every book offers a chance to try another life you could have lived.",
        "spl_available": True,
        "spl_branches": ["Capitol Hill", "Ballard", "West Seattle"],
        "checkouts": 478,
        "clubs_reading": 6,
    },
    {
        "id": 6,
        "title": "Don't Make Me Think",
        "author": "Steve Krug",
        "cover": "https://covers.openlibrary.org/b/isbn/9780321965516-L.jpg",
        "rating": 4.2,
        "rating_count": 7234,
        "genres": ["Design", "UX/UI", "Technology"],
        "description": "The classic guide to web usability, updated for modern apps and responsive design.",
        "spl_available": True,
        "spl_branches": ["Central Library"],
        "checkouts": 156,
        "clubs_reading": 1,
    },
]

books_by_id = {book["id"]: book for book in books}

clubs = [
    {
        "id": 1,
        "name": "Seattle Fantasy Readers",
        "description": "A welcoming group for fans of fantasy and speculative fiction.",
        "genre": "Fantasy",
        "location": "Capitol Hill, Seattle",
        "meeting_day": "First Saturday",
        "meeting_time": "2:00 PM",
        "members": 24,
        "current_book_id": 1,
        "thumbnail": "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600",
        "is_external": False,
    },
    {
        "id": 2,
        "name": "Ballard Book Club",
        "description": "A diverse reading group exploring literary fiction and non-fiction.",
        "genre": "Literary Fiction",
        "location": "Ballard, Seattle",
        "meeting_day": "Third Wednesday",
        "meeting_time": "7:00 PM",
        "members": 18,
        "current_book_id": 5,
        "thumbnail": "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=600",
        "is_external": False,
    },
    {
        "id": 3,
        "name": "UX Book Club Seattle",
        "description": "For designers and developers exploring UX/UI books.",
        "genre": "Design",
        "location": "South Lake Union, Seattle",
        "meeting_day": "Second Tuesday",
        "meeting_time": "6:30 PM",
        "members": 31,
        "current_book_id": 6,
        "thumbnail": "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600",
        "is_external": False,
    },
    {
        "id": 4,
        "name": "Fremont Sci-Fi Society",
        "description": "Hard sci-fi, soft sci-fi, and space opera.",
        "genre": "Science Fiction",
        "location": "Fremont, Seattle",
        "meeting_day": "Last Friday",
        "meeting_time": "6:00 PM",
        "members": 15,
        "current_book_id": 2,
        "thumbnail": "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=600",
        "is_external": False,
    },
]

user_club_ids = [1, 3]

library = {
    "saved": [3, 5],
    "in_progress": [1, 6],
    "finished": [2, 4],
}

forum_posts = [
    {
        "title": "What fantasy book changed your life?",
        "author": "Rayleigh M.",
        "genre": "Fantasy",
        "club": None,
        "replies": 23,
        "likes": 45,
        "time_ago": "2 hours ago",
        "preview": "I just finished The House in the Cerulean Sea and I am emotional. What books have hit you like that?",
    },
    {
        "title": "Best UX books for beginners?",
        "author": "Ben K.",
        "genre": "Design",
        "club": "UX Book Club Seattle",
        "replies": 15,
        "likes": 32,
        "time_ago": "5 hours ago",
        "preview": "Making a career switch into UX. Beyond Don't Make Me Think, what should I read first?",
    },
    {
        "title": "March reading schedule discussion",
        "author": "Sarah L.",
        "genre": None,
        "club": "Seattle Fantasy Readers",
        "replies": 8,
        "likes": 12,
        "time_ago": "1 day ago",
        "preview": "Should we do 3 chapters/week or 4? Let's vote before our next meeting.",
    },
]

genres = [
    "Fantasy",
    "Science Fiction",
    "Literary Fiction",
    "Mystery",
    "Non-Fiction",
    "Self-Help",
    "Design",
    "Historical Fiction",
    "Contemporary",
    "LGBTQ+",
    "Mythology",
    "Technology",
]

neighborhoods = [
    "Capitol Hill",
    "Ballard",
    "Fremont",
    "University District",
    "South Lake Union",
    "Downtown",
    "Beacon Hill",
    "Columbia City",
    "Ravenna",
    "West Seattle",
    "Greenwood",
    "Rainier Beach",
]
